language: node_js
node_js: '6'

os:
- linux
- osx
dist: xenial

env:
  global:
    - CC=clang CXX=clang++ npm_config_clang=1

branches:
  only:
  - master
  - /^v\d+\.\d+\.\d+/

before_script:
  # remove "electron" folder for electron-locater tests
  - cd ../../ && mv ./electron/electron-rebuild/ ./electron-rebuild/ && rm -rf ./electron/ && cd ./electron-rebuild/
