language: node_js
node_js:
- '6'
- '4'
os:
- linux
- osx

env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

branches:
  only:
  - master
  - /^v\d+\.\d+\.\d+/

script: npm run test