step-restore-cache: &step-restore-cache
  restore_cache:
    keys:
      - v1-dependencies-{{ arch }}-{{ checksum "package-lock.json" }}

steps-test: &steps-test
  steps:
    - checkout
    - *step-restore-cache
    - run:
        name: Install Node
        command: |
          case "$(uname -s)" in
            Darwin)
              curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
              export NVM_DIR="$HOME/.nvm"
              [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
              nvm install 10
              nvm alias default 10
              echo 'export NVM_DIR=${HOME}/.nvm' >> $BASH_ENV
              echo "[ -s '${NVM_DIR}/nvm.sh' ] && . '${NVM_DIR}/nvm.sh'" >> $BASH_ENV
              ;;
            Windows*|CYGWIN*|MINGW*|MSYS*)
              nvm install 10.22.0
              nvm use 10.22.0
              ;;
          esac
    - run: npm install --engine-strict
    - save_cache:
        paths:
          - node_modules
        key: v1-dependencies-{{ arch }}-{{ checksum "package-lock.json" }}
    - run: npm run lint
    - run: npm run coverage
    - run: npm run codecov


version: 2.1
orbs:
  win: circleci/windows@1.0.0
jobs:
  test-linux-10:
    docker:
      - image: circleci/node:10
    <<: *steps-test
  test-linux-12:
    docker:
      - image: circleci/node:12
    <<: *steps-test
  test-linux-14:
    docker:
      - image: circleci/node:14
    <<: *steps-test
  test-mac:
    macos:
      xcode: "12.2.0"
    <<: *steps-test
  test-windows:
    executor:
      name: win/vs2019
      shell: bash.exe
    environment:
      GYP_MSVS_VERSION: '2019'
    <<: *steps-test

  release:
    docker:
      - image: circleci/node:10.22
    steps:
      - checkout
      - *step-restore-cache
      - run: npm install
      - run: npx semantic-release
workflows:
  version: 2
  test_and_release:
    # Run the test jobs first, then the release only when all the test jobs are successful
    jobs:
      - test-linux-10
      - test-linux-12
      - test-linux-14
      - test-mac
      - test-windows
      - release:
          requires:
            - test-linux-10
            - test-linux-12
            - test-linux-14
            - test-mac
            - test-windows
          filters:
            branches:
              only:
                - master
